# Generated by Django 5.2.9 on 2026-03-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="资产名称")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("real_estate", "房产"),
                            ("vehicle", "车辆"),
                            ("stock", "股票"),
                            ("fund", "基金"),
                            ("deposit", "存款"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="当前价值"
                    ),
                ),
                (
                    "purchase_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="购入价值"
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="购入日期")),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "资产",
                "verbose_name_plural": "资产",
                "db_table": "assets",
                "ordering": ["-created_at"],
            },
        ),
    ]
