# Generated by Django 5.2.9 on 2026-03-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "收入"),
                            ("expense", "支出"),
                            ("transfer", "转账"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="金额"
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="分类")),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                ("transaction_date", models.DateField(verbose_name="交易日期")),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "流水",
                "verbose_name_plural": "流水",
                "db_table": "transactions",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
