# Generated by Django 5.2.9 on 2026-03-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="目标名称")),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="目标金额"
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="当前金额",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="截止日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("abandoned", "已放弃"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "财务目标",
                "verbose_name_plural": "财务目标",
                "db_table": "goals",
                "ordering": ["-created_at"],
            },
        ),
    ]
