# Generated by Django 5.2.9 on 2026-03-28 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100, verbose_name='来源名称')),
                ('source_type', models.CharField(choices=[('income', '收入'), ('account', '账户'), ('expense', '支出'), ('asset', '资产'), ('liability', '负债'), ('goal', '目标')], max_length=20, verbose_name='来源类型')),
                ('target_name', models.CharField(max_length=100, verbose_name='去向名称')),
                ('target_type', models.CharField(choices=[('income', '收入'), ('account', '账户'), ('expense', '支出'), ('asset', '资产'), ('liability', '负债'), ('goal', '目标')], max_length=20, verbose_name='去向类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额')),
                ('flow_date', models.DateField(verbose_name='流向日期')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flow_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '资金流向记录',
                'verbose_name_plural': '资金流向记录',
                'db_table': 'stats_flow_records',
                'ordering': ['-flow_date', '-created_at'],
            },
        ),
    ]
