# Generated by Django 5.2.9 on 2026-03-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="账户名称")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("cash", "现金"),
                            ("debit_card", "储蓄卡"),
                            ("credit_card", "信用卡"),
                            ("alipay", "支付宝"),
                            ("wechat", "微信钱包"),
                            ("investment", "投资账户"),
                            ("other", "其他"),
                        ],
                        default="debit_card",
                        max_length=20,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="余额"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="币种"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "账户",
                "verbose_name_plural": "账户",
                "db_table": "accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
