# Generated by Django 5.2.9 on 2026-03-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Liability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="负债名称")),
                (
                    "liability_type",
                    models.CharField(
                        choices=[
                            ("mortgage", "房贷"),
                            ("car_loan", "车贷"),
                            ("credit_card", "信用卡欠款"),
                            ("personal_loan", "个人借款"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="总金额"
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="剩余金额"
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=6, verbose_name="年利率"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="到期日"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "负债",
                "verbose_name_plural": "负债",
                "db_table": "liabilities",
                "ordering": ["-created_at"],
            },
        ),
    ]
